### ISSUE TITLE
[Character Control] Roll, Jump 후 굴러가는 애니메이션 재생

### ISSUE THREAD

**Issue by calculus12** [calculus12/Find-A-New-Home#4]
캐릭터 컨트롤 할때 좌 우로 움직일때는 괜찮으나 Jump, Roll 후에 굴러가는 애니메이션이 재생되는 이슈가 있습니다.

**Comment by JoonkyuJang** [comment]
특징을 주기 위해서 일부러 구르는 애니메이션을 재생하는 거라 이슈는 아닙니다. 제거하는게 좋을까요?

**Comment by JoonkyuJang** [comment]
커밋 [e6098cd](https://github.com/calculus12/Find-A-New-Home/commit/e6098cd0fd18209e9bc32ee72544127dec59aef5)에서 해결됐습니다. animation controller가 반영되지 않았던 것이 문제였습니다
