### ISSUE TITLE
[Character Control, UI] 게임 일시정지 후 다시시작을 눌렀을 때 캐릭터 이동

### ISSUE THREAD

**Issue by calculus12** [calculus12/Find-A-New-Home#5]
게임 플레이 중 일시정지 후 continue 했을 때 임의로 움직이는 이슈가 있습니다.

**Comment by JoonkyuJang** [comment]
커밋 [3a2ccc9](https://github.com/calculus12/Find-A-New-Home/commit/3a2ccc9ee52306f23b1786e8346643a5d1983ff5)에서 해결됨
